version: '3.1'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/usr/src/app/src/
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://interviewapp:pass@postgres/interview
      PORT: 8080
      HOST: 0.0.0.0
    command: ["nodemon", "src/app.js"]
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: interviewapp
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: interview